name: 'Setup Ruby Pkgs'
description: 'Cross platform action for setting up Ruby build environments'
author: 'MSP-Greg'
inputs:
  ruby-version:
    description: 'Ruby version'
    default: ''
  apt-get:
    description: 'Ubuntu - install packages'
    default: ''
  brew:
    description: 'macOS - install packages'
    default: ''
  mingw:
    description: 'MinGW - install MSYS2 mingw64 packages'
    default: ''
  msys2:
    description: 'MinGW - install MSYS2 msys2 packages'
    default: ''
  mswin:
    description: 'mswin - install MSYS2 packages (mingw64 packages need prefix)'
    default: ''
  choco:
    description: 'mswin - install Chocolatey packages'
    default: ''
  vcpkg:
    description: 'mswin - install vcpkg packages'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
