name: 'Setup Ruby Pkgs'
description: 'Cross platorm action for setting up Ruby build environments'
author: 'MSP-Greg'
inputs:
  apt-get:
    description: 'Install Ubuntu packages'
    default: ''
  brew:
    description: 'Install macOS packages'
    default: ''
  mingw:
    description: 'Install MSYS2 mingw64 packages'
    default: ''
  msys2:
    description: 'Install MSYS2 msys2 packages'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
