name: 'Setup Ruby Pkgs'
description: 'Cross platform action for setting up Ruby build environments'
author: 'MSP-Greg'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: false
    default: 'default'
  bundler:
    description: 'The version of Bundler to install. Either none, 1, 2, latest or Gemfile.lock. The default tries Gemfile.lock and otherwise uses latest.'
    required: false
    default: 'default'
  working-directory:
    description: 'The working directory to use for resolving paths for .ruby-version, .tool-versions and Gemfile.lock.'
    required: false
    default: '.'
  apt-get:
    description: 'Ubuntu - install packages'
    default: ''
  brew:
    description: 'macOS - install packages'
    default: ''
  mingw:
    description: 'MinGW - install MSYS2 mingw64 packages'
    default: ''
  msys2:
    description: 'MinGW - install MSYS2 msys2 packages'
    default: ''
  mswin:
    description: 'mswin - install MSYS2 packages (mingw64 packages need prefix)'
    default: ''
  choco:
    description: 'mswin - install Chocolatey packages'
    default: ''
  vcpkg:
    description: 'mswin - install vcpkg packages'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
