name: CI

on: [push]

jobs:
  win32:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        # ruby: [ ruby-head, mingw, mswin, 2.4, 2.2 ]
        ruby: [ mingw, 2.5, 2.4, 2.3, 2.2 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Install
        uses: ./
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl ragel

      - name: Info
        run:  |
          ruby -v
          echo ''
          gcc --version
          echo ''
          openssl version
          echo ''
          ragel --version
          echo ''
          if ('${{ matrix.ruby }}' -ge '2.4') {
            ridk version
          }
