name: CI

on: [push, pull_request]

jobs:
  win32:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows ]
        ruby: [ mswin, mingw, 2.5, 2.4, 2.3, 2.2 ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Install
        uses: ./
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl ragel
          mswin: bison mingw-w64-x86_64-ragel
          vcpkg: readline
          setup-ruby-ref: MSP-Greg/ruby-setup-ruby/bundler-cache

      - name: Info
        run:  |
          # stderr output from OpenSSL causes failure
          $ErrorActionPreference = 'Continue'
          ruby -v
          echo ''
          gcc --version
          echo ''
          openssl version
          echo ''
          ragel --version
          echo ''
          if ('${{ matrix.ruby }}' -ge '2.4') {
            ridk version
          }

      - name: gem install openssl
        if:   (matrix.ruby >= '2.4') && (matrix.ruby <= '3.2')
        run:  |
          gem install openssl -N
          ruby -ropenssl -e "puts 'Built with: ' + OpenSSL::OPENSSL_VERSION"
          ruby -ropenssl -e "puts 'Running:    ' + OpenSSL::OPENSSL_LIBRARY_VERSION"

      - name: dir msys2 package cache
        run: dir d:\a\_temp\pacman\pkg
